### ISSUE TITLE
Don't work with Create 0.5.1

### ISSUE THREAD

**Issue by ClashofCraft972** [zaftnotameni/creatania#12]
Hi, a few days ago Create released a new version which made add-ons don't work.
Can you do a quick update to fix that please ?

TY and have a nice day

**Comment by ClaudiusMinimus** [comment]
zaftnotameni has not replied to my messages and I am looking for a Java developer to take over this project, though I will need to fork it. I may have someone who can start in a few weeks, so hopefully, it can be updated. However, I am not sure we will be able to update the 1.18.2 version. The plan is to port to 1.19.2 for Forge and Fabric.

**Comment by ClashofCraft972** [comment]
Hum, Okay, I'm playing with a 1.18.2 version, so it's a little sad, thank you for your answer and maybe one day I'll play with this :)

Anyway thank you
